Refactor `eagle.visualization` module and get diff plots working (#132)

diff --git a/.github/workflows/nested_eagle.yml b/.github/workflows/nested_eagle.yml
--- a/.github/workflows/nested_eagle.yml
+++ b/.github/workflows/nested_eagle.yml
@@ -277,7 +277,7 @@ jobs:
 
           for truth in grid obs; do
             for extent in global lam; do
-              dir=$RUNROOT/visualization/grid2$truth/$extent
+              dir=$RUNROOT/visualization/grid2$truth/$extent/plots-basic
               count=$(ls -1 $dir/*.png | wc -l)
               expected=8
               test $count -eq $expected || {
@@ -287,9 +287,19 @@ jobs:
             done
           done
 
+          for extent in global lam; do
+            dir=$RUNROOT/visualization/grid2grid/$extent/plots-spatial-stats
+            count=$(ls -1 $dir/*.png | wc -l)
+            expected=40
+            test $count -eq $expected || {
+              echo "ERROR: Found $count PNG files in $dir, expected $expected"
+              exit 1
+            }
+          done
+
           # Done.
 
-          echo "Nested EAGLE CI pipeline completed successfully."
+          echo Nested EAGLE CI pipeline completed successfully.
 
   cleanup_label:
     name: Cleanup ci-running label
